Replace slack references with Discord
deta/cloud-docs pull request #208
Opened 2022-05-07 19:39 UTC by harshitsinghai77

Discord Slack workplace has been deleted.

2022-05-09 08:55 UTC, abdelhai requested changes
hi, thanks for the pr! just used the canonical url instead of a direct one

2022-05-09 08:55 UTC, abdelhai commented on docs/home.md
> +- [Discord](https://discord.gg/cGZV5Shc)
```suggestion
- [Discord](https://go.deta.dev/discord)
```

2022-05-09 08:55 UTC, abdelhai commented on docs/micros/custom_domains.md
> +If you had to change something from the steps mentioned above, [email us](<mailto:aavash@deta.sh?subject=Re-enable custom domain>) or [let us know in discord](https://discord.gg/cGZV5Shc). This is im
```suggestion
If you had to change something from the steps mentioned above, [email us](<mailto:aavash@deta.sh?subject=Re-enable custom domain>) or [let us know in discord](https://go.deta.dev/discord). This is important as our systems eventually stop trying to assign the custom domain on errors. Manual re-enabling of the domain might be required.
```

2022-05-09 08:55 UTC, abdelhai commented on docusaurus.config.js
> +              href: 'https://discord.gg/cGZV5Shc',
```suggestion
              href: 'https://go.deta.dev/discord',
```

2022-05-09 09:08 UTC, harshitsinghai77 commented
Done.

2022-05-09 09:24 UTC, abdelhai approved these changes
thank you! @harshitsinghai77

2022-05-12 00:20 UTC, harshitsinghai77 commented
@abdelhai when do approve PRs get merged?

2022-05-17 20:10 UTC, merged

2022-05-17 20:10 UTC, abdelhai commented
hi @harshitsinghai77 apology, totally missed that merge button XD